type BgLang = 'ko' | 'en' | 'ja' | 'zh' | 'fr' | 'de' | 'es' | 'it' | 'pt' | 'ru' | 'ar' | 'hi' | 'th' | 'vi' | 'id';

interface BgStringMap {
  fetchingSubtitles: string;
  subtitlesLoaded: (count: number) => string;
  translating: (done: number, total: number, pct: number) => string;
  noSubtitles: string;
  noModel: string;
  modelLoadFailed: string;
  memoryAbort: string;
  bgCancelledRetry: string;
  translationError: string;
  translationFailed: string;
  failNoSubtitles: string;
  failNoModel: string;
  failModelLoad: string;
  failMemory: string;
  failCancelled: string;
}

const STRINGS: Record<BgLang, BgStringMap> = {
  ko: {
    fetchingSubtitles:  '자막 가져오는 중...',
    subtitlesLoaded:    (n) => `자막 ${n}개 로드 완료`,
    translating:        (done, total, pct) => `번역 중... ${done}/${total} (${pct}%)`,
    noSubtitles:        '자막 없음',
    noModel:            '모델 파일 없음',
    modelLoadFailed:    '모델 로드 실패',
    memoryAbort:        '메모리 부족 — 재시작 시 이어서 번역됩니다',
    bgCancelledRetry:   'BG 번역 취소됨 (재시도 실패)',
    translationError:   '번역 오류',
    translationFailed:  '번역 실패',
    failNoSubtitles:    '자막 없음',
    failNoModel:        '모델 파일 없음',
    failModelLoad:      '모델 로드 실패',
    failMemory:         '메모리 부족 (재시작 시 재개)',
    failCancelled:      'BG 번역 취소됨 (재시도 실패)',
  },
  en: {
    fetchingSubtitles:  'Fetching subtitles...',
    subtitlesLoaded:    (n) => `${n} subtitles loaded`,
    translating:        (done, total, pct) => `Translating... ${done}/${total} (${pct}%)`,
    noSubtitles:        'No subtitles',
    noModel:            'Model file not found',
    modelLoadFailed:    'Model load failed',
    memoryAbort:        'Low memory — will resume on restart',
    bgCancelledRetry:   'BG translation cancelled (retry failed)',
    translationError:   'Translation error',
    translationFailed:  'Translation failed',
    failNoSubtitles:    'No subtitles',
    failNoModel:        'Model file not found',
    failModelLoad:      'Model load failed',
    failMemory:         'Low memory (will resume)',
    failCancelled:      'BG translation cancelled (retry failed)',
  },
  ja: {
    fetchingSubtitles:  '字幕を取得中...',
    subtitlesLoaded:    (n) => `字幕 ${n}件 読み込み完了`,
    translating:        (done, total, pct) => `翻訳中... ${done}/${total} (${pct}%)`,
    noSubtitles:        '字幕なし',
    noModel:            'モデルファイルが見つかりません',
    modelLoadFailed:    'モデルの読み込みに失敗しました',
    memoryAbort:        'メモリ不足 — 再起動時に再開します',
    bgCancelledRetry:   'BG翻訳がキャンセルされました（再試行失敗）',
    translationError:   '翻訳エラー',
    translationFailed:  '翻訳失敗',
    failNoSubtitles:    '字幕なし',
    failNoModel:        'モデルファイルが見つかりません',
    failModelLoad:      'モデルの読み込み失敗',
    failMemory:         'メモリ不足（再起動時に再開）',
    failCancelled:      'BG翻訳キャンセル（再試行失敗）',
  },
  zh: {
    fetchingSubtitles:  '正在获取字幕...',
    subtitlesLoaded:    (n) => `已加载 ${n} 条字幕`,
    translating:        (done, total, pct) => `翻译中... ${done}/${total} (${pct}%)`,
    noSubtitles:        '无字幕',
    noModel:            '找不到模型文件',
    modelLoadFailed:    '模型加载失败',
    memoryAbort:        '内存不足 — 重启后将继续翻译',
    bgCancelledRetry:   '后台翻译已取消（重试失败）',
    translationError:   '翻译错误',
    translationFailed:  '翻译失败',
    failNoSubtitles:    '无字幕',
    failNoModel:        '找不到模型文件',
    failModelLoad:      '模型加载失败',
    failMemory:         '内存不足（重启后继续）',
    failCancelled:      '后台翻译取消（重试失败）',
  },
  fr: {
    fetchingSubtitles:  'Récupération des sous-titres...',
    subtitlesLoaded:    (n) => `${n} sous-titres chargés`,
    translating:        (done, total, pct) => `Traduction... ${done}/${total} (${pct}%)`,
    noSubtitles:        'Pas de sous-titres',
    noModel:            'Fichier modèle introuvable',
    modelLoadFailed:    'Échec du chargement du modèle',
    memoryAbort:        'Mémoire insuffisante — reprendra au redémarrage',
    bgCancelledRetry:   'Traduction BG annulée (échec de la nouvelle tentative)',
    translationError:   'Erreur de traduction',
    translationFailed:  'Traduction échouée',
    failNoSubtitles:    'Pas de sous-titres',
    failNoModel:        'Fichier modèle introuvable',
    failModelLoad:      'Échec du chargement',
    failMemory:         'Mémoire insuffisante (reprise au redémarrage)',
    failCancelled:      'Traduction BG annulée',
  },
  de: {
    fetchingSubtitles:  'Untertitel werden abgerufen...',
    subtitlesLoaded:    (n) => `${n} Untertitel geladen`,
    translating:        (done, total, pct) => `Übersetze... ${done}/${total} (${pct}%)`,
    noSubtitles:        'Keine Untertitel',
    noModel:            'Modelldatei nicht gefunden',
    modelLoadFailed:    'Modell konnte nicht geladen werden',
    memoryAbort:        'Wenig Speicher — wird beim Neustart fortgesetzt',
    bgCancelledRetry:   'BG-Übersetzung abgebrochen (Wiederholung fehlgeschlagen)',
    translationError:   'Übersetzungsfehler',
    translationFailed:  'Übersetzung fehlgeschlagen',
    failNoSubtitles:    'Keine Untertitel',
    failNoModel:        'Modelldatei nicht gefunden',
    failModelLoad:      'Modellladen fehlgeschlagen',
    failMemory:         'Wenig Speicher (wird fortgesetzt)',
    failCancelled:      'BG-Übersetzung abgebrochen',
  },
  es: {
    fetchingSubtitles:  'Obteniendo subtítulos...',
    subtitlesLoaded:    (n) => `${n} subtítulos cargados`,
    translating:        (done, total, pct) => `Traduciendo... ${done}/${total} (${pct}%)`,
    noSubtitles:        'Sin subtítulos',
    noModel:            'Archivo de modelo no encontrado',
    modelLoadFailed:    'Error al cargar el modelo',
    memoryAbort:        'Memoria insuficiente — se reanudará al reiniciar',
    bgCancelledRetry:   'Traducción BG cancelada (reintento fallido)',
    translationError:   'Error de traducción',
    translationFailed:  'Traducción fallida',
    failNoSubtitles:    'Sin subtítulos',
    failNoModel:        'Archivo de modelo no encontrado',
    failModelLoad:      'Error al cargar modelo',
    failMemory:         'Memoria insuficiente (se reanudará)',
    failCancelled:      'Traducción BG cancelada',
  },
  it: {
    fetchingSubtitles:  'Recupero sottotitoli...',
    subtitlesLoaded:    (n) => `${n} sottotitoli caricati`,
    translating:        (done, total, pct) => `Traduzione... ${done}/${total} (${pct}%)`,
    noSubtitles:        'Nessun sottotitolo',
    noModel:            'File modello non trovato',
    modelLoadFailed:    'Caricamento modello fallito',
    memoryAbort:        'Memoria insufficiente — riprenderà al riavvio',
    bgCancelledRetry:   'Traduzione BG annullata (nuovo tentativo fallito)',
    translationError:   'Errore di traduzione',
    translationFailed:  'Traduzione fallita',
    failNoSubtitles:    'Nessun sottotitolo',
    failNoModel:        'File modello non trovato',
    failModelLoad:      'Caricamento fallito',
    failMemory:         'Memoria insufficiente (riprende al riavvio)',
    failCancelled:      'Traduzione BG annullata',
  },
  pt: {
    fetchingSubtitles:  'Buscando legendas...',
    subtitlesLoaded:    (n) => `${n} legendas carregadas`,
    translating:        (done, total, pct) => `Traduzindo... ${done}/${total} (${pct}%)`,
    noSubtitles:        'Sem legendas',
    noModel:            'Arquivo de modelo não encontrado',
    modelLoadFailed:    'Falha ao carregar o modelo',
    memoryAbort:        'Memória insuficiente — continuará ao reiniciar',
    bgCancelledRetry:   'Tradução BG cancelada (nova tentativa falhou)',
    translationError:   'Erro de tradução',
    translationFailed:  'Tradução falhou',
    failNoSubtitles:    'Sem legendas',
    failNoModel:        'Arquivo de modelo não encontrado',
    failModelLoad:      'Falha ao carregar modelo',
    failMemory:         'Memória insuficiente (continuará)',
    failCancelled:      'Tradução BG cancelada',
  },
  ru: {
    fetchingSubtitles:  'Загрузка субтитров...',
    subtitlesLoaded:    (n) => `Загружено субтитров: ${n}`,
    translating:        (done, total, pct) => `Перевод... ${done}/${total} (${pct}%)`,
    noSubtitles:        'Субтитры отсутствуют',
    noModel:            'Файл модели не найден',
    modelLoadFailed:    'Ошибка загрузки модели',
    memoryAbort:        'Мало памяти — возобновится при перезапуске',
    bgCancelledRetry:   'Фоновый перевод отменён (повтор не удался)',
    translationError:   'Ошибка перевода',
    translationFailed:  'Перевод не удался',
    failNoSubtitles:    'Субтитры отсутствуют',
    failNoModel:        'Файл модели не найден',
    failModelLoad:      'Ошибка загрузки модели',
    failMemory:         'Мало памяти (возобновится)',
    failCancelled:      'Фоновый перевод отменён',
  },
  ar: {
    fetchingSubtitles:  'جارٍ جلب الترجمات...',
    subtitlesLoaded:    (n) => `تم تحميل ${n} ترجمة`,
    translating:        (done, total, pct) => `جارٍ الترجمة... ${done}/${total} (${pct}%)`,
    noSubtitles:        'لا توجد ترجمات',
    noModel:            'ملف النموذج غير موجود',
    modelLoadFailed:    'فشل تحميل النموذج',
    memoryAbort:        'ذاكرة غير كافية — سيُستأنف عند إعادة التشغيل',
    bgCancelledRetry:   'تم إلغاء الترجمة (فشلت إعادة المحاولة)',
    translationError:   'خطأ في الترجمة',
    translationFailed:  'فشلت الترجمة',
    failNoSubtitles:    'لا توجد ترجمات',
    failNoModel:        'ملف النموذج غير موجود',
    failModelLoad:      'فشل التحميل',
    failMemory:         'ذاكرة غير كافية (سيُستأنف)',
    failCancelled:      'تم إلغاء الترجمة',
  },
  hi: {
    fetchingSubtitles:  'उपशीर्षक प्राप्त हो रहे हैं...',
    subtitlesLoaded:    (n) => `${n} उपशीर्षक लोड हुए`,
    translating:        (done, total, pct) => `अनुवाद हो रहा है... ${done}/${total} (${pct}%)`,
    noSubtitles:        'कोई उपशीर्षक नहीं',
    noModel:            'मॉडल फ़ाइल नहीं मिली',
    modelLoadFailed:    'मॉडल लोड विफल',
    memoryAbort:        'कम मेमोरी — पुनः आरंभ पर जारी रहेगा',
    bgCancelledRetry:   'BG अनुवाद रद्द (पुनः प्रयास विफल)',
    translationError:   'अनुवाद त्रुटि',
    translationFailed:  'अनुवाद विफल',
    failNoSubtitles:    'कोई उपशीर्षक नहीं',
    failNoModel:        'मॉडल फ़ाइल नहीं मिली',
    failModelLoad:      'मॉडल लोड विफल',
    failMemory:         'कम मेमोरी (जारी रहेगा)',
    failCancelled:      'BG अनुवाद रद्द',
  },
  th: {
    fetchingSubtitles:  'กำลังดึงคำบรรยาย...',
    subtitlesLoaded:    (n) => `โหลดคำบรรยาย ${n} รายการแล้ว`,
    translating:        (done, total, pct) => `กำลังแปล... ${done}/${total} (${pct}%)`,
    noSubtitles:        'ไม่มีคำบรรยาย',
    noModel:            'ไม่พบไฟล์โมเดล',
    modelLoadFailed:    'โหลดโมเดลล้มเหลว',
    memoryAbort:        'หน่วยความจำไม่เพียงพอ — จะดำเนินการต่อเมื่อรีสตาร์ท',
    bgCancelledRetry:   'การแปล BG ถูกยกเลิก (ลองใหม่ล้มเหลว)',
    translationError:   'ข้อผิดพลาดในการแปล',
    translationFailed:  'การแปลล้มเหลว',
    failNoSubtitles:    'ไม่มีคำบรรยาย',
    failNoModel:        'ไม่พบไฟล์โมเดล',
    failModelLoad:      'โหลดโมเดลล้มเหลว',
    failMemory:         'หน่วยความจำไม่เพียงพอ (จะดำเนินการต่อ)',
    failCancelled:      'การแปล BG ถูกยกเลิก',
  },
  vi: {
    fetchingSubtitles:  'Đang tải phụ đề...',
    subtitlesLoaded:    (n) => `Đã tải ${n} phụ đề`,
    translating:        (done, total, pct) => `Đang dịch... ${done}/${total} (${pct}%)`,
    noSubtitles:        'Không có phụ đề',
    noModel:            'Không tìm thấy file mô hình',
    modelLoadFailed:    'Tải mô hình thất bại',
    memoryAbort:        'Bộ nhớ không đủ — sẽ tiếp tục khi khởi động lại',
    bgCancelledRetry:   'Dịch nền bị hủy (thử lại thất bại)',
    translationError:   'Lỗi dịch thuật',
    translationFailed:  'Dịch thất bại',
    failNoSubtitles:    'Không có phụ đề',
    failNoModel:        'Không tìm thấy file mô hình',
    failModelLoad:      'Tải mô hình thất bại',
    failMemory:         'Bộ nhớ không đủ (sẽ tiếp tục)',
    failCancelled:      'Dịch nền bị hủy',
  },
  id: {
    fetchingSubtitles:  'Mengambil subtitle...',
    subtitlesLoaded:    (n) => `${n} subtitle dimuat`,
    translating:        (done, total, pct) => `Menerjemahkan... ${done}/${total} (${pct}%)`,
    noSubtitles:        'Tidak ada subtitle',
    noModel:            'File model tidak ditemukan',
    modelLoadFailed:    'Gagal memuat model',
    memoryAbort:        'Memori tidak cukup — akan dilanjutkan saat restart',
    bgCancelledRetry:   'Terjemahan BG dibatalkan (percobaan ulang gagal)',
    translationError:   'Kesalahan terjemahan',
    translationFailed:  'Terjemahan gagal',
    failNoSubtitles:    'Tidak ada subtitle',
    failNoModel:        'File model tidak ditemukan',
    failModelLoad:      'Gagal memuat model',
    failMemory:         'Memori tidak cukup (akan dilanjutkan)',
    failCancelled:      'Terjemahan BG dibatalkan',
  },
};

const FALLBACK_LANG: BgLang = 'ko';

function normalizeLang(lang: string | undefined | null): BgLang {
  if (!lang) return FALLBACK_LANG;
  const lower = lang.toLowerCase();
  const nameMap: Record<string, BgLang> = {
    korean: 'ko', japanese: 'ja', chinese: 'zh', spanish: 'es',
    french: 'fr', german: 'de', italian: 'it', portuguese: 'pt',
    russian: 'ru', arabic: 'ar', hindi: 'hi', thai: 'th',
    vietnamese: 'vi', indonesian: 'id', english: 'en',
  };
  if (nameMap[lower]) return nameMap[lower];
  const code = lower.split('-')[0] as BgLang;
  return STRINGS[code] ? code : FALLBACK_LANG;
}

export function getBgStrings(language: string | undefined | null): BgStringMap {
  return STRINGS[normalizeLang(language)];
}